# Generated by Django 5.2 on 2025-04-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('format_type', models.CharField(choices=[('video', 'Видео'), ('audio', 'Аудио')], max_length=10)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('quality', models.CharField(default='720p', max_length=20)),
                ('resolution', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
